//! UI components built on top of the rendering layer

mod button;
mod checkbox;
mod dropdown;
mod label;
mod layout;
mod panel;
pub mod remote;
mod textbox;

pub use button::Button;
pub use checkbox::Checkbox;
pub use dropdown::Dropdown;
pub use label::Label;
pub use layout::{CrossAlignment, HorizontalLayout, LayoutElement, VerticalLayout};
pub use panel::Panel;
pub use remote::{
    RemoteCommand, RemoteCommandChannel, RemoteError, RemoteSessionReport, RemoteTransportError,
    RemoteUiHost, RemoteUiSession,
};
pub use textbox::TextBox;

use glam::Vec2;

/// Mouse buttons supported by the UI system
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
}

/// State of a button input
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ButtonState {
    Pressed,
    Released,
}

/// Subset of keyboard keys used by widgets
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyCode {
    Backspace,
    Other,
}

/// High-level UI events handled by widgets
#[derive(Debug, Clone)]
pub enum UiEvent {
    CursorMoved {
        position: Vec2,
    },
    MouseButton {
        button: MouseButton,
        state: ButtonState,
        position: Vec2,
    },
    Scroll {
        delta: f32,
        position: Vec2,
    },
    CharacterInput(char),
    KeyInput {
        key: KeyCode,
    },
}

/// Events generated by widgets while handling input
#[derive(Debug, Clone)]
pub enum WidgetEvent {
    ButtonClicked { label: String },
    CheckboxToggled { label: String, checked: bool },
    TextChanged { text: String },
    TextBoxFocusChanged { focused: bool },
    DropdownSelectionChanged { id: String, selected: String },
    PanelDragStarted,
    PanelDragged { position: Vec2 },
    PanelDragEnded,
    PanelToggleChanged { collapsed: bool },
}

/// Common trait for UI components
pub trait Widget {
    /// Draws the widget
    fn draw(&self, renderer: &crate::renderer::QuadRenderer);

    /// Returns a human-readable widget type name
    fn type_name(&self) -> &'static str;

    /// Handles incoming UI events. Returns an optional event generated by the widget.
    fn handle_event(&mut self, _event: &UiEvent) -> Option<WidgetEvent> {
        None
    }

    /// Returns the position of the widget
    fn position(&self) -> Vec2;

    /// Returns the size of the widget
    fn size(&self) -> Vec2;

    /// Checks if a point is inside the widget bounds
    fn contains_point(&self, point: Vec2) -> bool {
        let pos = self.position();
        let size = self.size();
        point.x >= pos.x
            && point.x <= pos.x + size.x
            && point.y >= pos.y
            && point.y <= pos.y + size.y
    }
}
